name: a2_s08_inicio

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  tarea-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Ejecutar script de prueba
        run: echo "El workflow se ha ejecutado correctamente."