name: a3_s08_cache
on:
  workflow_dispatch:

jobs:
  a3_s08_sin_cache:
    name: Ejemplo_cache
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          # cache: 'npm'

      - name: Instalar dependencias
        run: |
          npm ci
          echo "job sin cache: descarga las dependencias cada vez"

      - name: Instalar dependencias
        run: npm i express