name: a3_s08_cache
on:
  workflow_dispatch:

jobs:
  node_cache:
    name: ejemplo_node
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm' # ACTIVA LA CACHÉ

      - name: Instalar dependencias
        run: |
          npm ci
          npm i express
          echo "npm ok"

  txt_keycache:
    name: ejemplo_txt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4
        with:
          path: carpeta_descarga
          key: mi-archivo-pesado

      - name: Descargar
        run: |
          mkdir -p carpeta_descarga
          for i in {1..9}
          do
            archivo="carpeta_descarga/txt_$i.txt"
            if [ -f "$archivo" ]; then
              echo "txt $i ok"
            else
              # Escribimos texto real dentro del archivo para que tenga peso (bytes)
              echo "Este es el texto del archivo numero $i" > "$archivo"
              echo "descarga txt ok."
            fi
          done

#      - name: Cache
#        uses: actions/cache@v4
#        with:
#          path: carpeta_descarga
#          key: mi-archivo-pesado
#
#      - name: Descargar
#        run: |
#          mkdir -p carpeta_descarga
#          for i in {1..9}
#          do
#          archivo="carpeta_descarga/txt_$i.txt"
#          if [ -f "$archivo" ]; then
#            echo "txt $i ok"
#          else
#            curl -L -o "$archivo" https://hetzner.de
#            echo "descarga txt ok."
#          fi
#          done