name: a3_s08_cache
on:
  workflow_dispatch:

jobs:
  node_cache:
    name: ejemplo_node
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm' # ACTIVA LA CACHÉ

      - name: Instalar dependencias
        run: |
          npm ci
          npm i express
          echo "npm ok"

  txt_keycache:
    name: ejemplo_txt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Descargar
        run: |
          if [ -f carpeta_descargas/archivo_grande.txt ]; then
            echo "txt ok"
          else
            echo "caché vacía, descargando txt grande..."
            mkdir -p carpeta_descargas
            curl -L -o carpeta_descargas/archivo_grande.txt https://hetzner.de
            echo "descarga txt ok."
          fi