name: a4_s08_cache
on:
  workflow_dispatch:
jobs:
  activar-otro:
    runs-on: ubuntu-latest
    steps:
      - name: Activar Flujo Destino
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'a2_s08_inicio.yml',
              ref: 'main'
            })